module Shikimori
  module API
    class V1
      module Forums
        attr_reader rest: REST

        def forums: (?headers: Hash[String, String] | nil, **untyped) -> untyped

        private

        def base_url: -> ::Shikimori::API::URI
      end
    end
  end
end
