module Shikimori
  module API
    class V1
      module Messages
        attr_reader rest: REST

        def message: (_ToS, ?headers: Hash[String, String] | nil, **untyped) -> untyped
        def create_message: ({ body: String, from_id: Integer, to_id: Integer, kind: 'Private' | nil }, ?frontend: 'false' | 'true' | 1 | 0 | nil, ?headers: Hash[String, String] | nil, **untyped) -> untyped
        def update_message: (_ToS, { body: String }, ?headers: Hash[String, String] | nil, **untyped) -> untyped
        def delete_message: (_ToS, ?headers: Hash[String, String] | nil, **untyped) -> untyped
        def read_all_messages: (type: 'news' | 'notifications', ?frontend: 'false' | 'true' | 1 | 0 | nil, ?headers: Hash[String, String] | nil, **untyped) -> untyped
        def delete_all_messages: (type: 'news' | 'notifications', ?frontend: 'false' | 'true' | 1 | 0 | nil, ?headers: Hash[String, String] | nil, **untyped) -> untyped

        private

        def base_url: -> ::Shikimori::API::URI
      end
    end
  end
end
