module Shikimori
  module API
    class RequestError < StandardError
    end

    class NotFoundError < RequestError
    end

    class ForbiddenError < RequestError
    end

    class BadRequestError < RequestError
    end
  end
end
