# Extensions
plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

Performance:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0

Naming/FileName:
  Exclude:
    - lib/*.rb

Naming/PredicateMethod:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']
  Max: 20

Metrics/ClassLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc', 'hash']

RSpec/ExampleLength:
  CountAsOne: ['array', 'heredoc', 'hash']

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

RSpec/SpecFilePathFormat:
  Enabled: false
