module Shikimori
  module API
    class V2
      module UserIgnore
        attr_reader rest: REST

        def create_user_ignore: (_ToS, ?headers: Hash[String, String] | nil, **untyped) -> untyped
        def delete_user_ignore: (_ToS, ?headers: Hash[String, String] | nil, **untyped) -> bool

        private

        def base_url: -> ::Shikimori::API::URI
      end
    end
  end
end
