module Shikimori
  module API
    class Client
      DEFAULT_SITE_URL: String

      attr_reader v1: V1
      attr_reader v2: V2

      def initialize: (?String site, **untyped) -> void

      def self.as_app: (?String site, **untyped) { (Shikimori::API::Client) -> void } -> Shikimori::API::Client
    end
  end
end
